name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'

    - name: Install Dependencies
      run: go mod tidy

    - name: Run Tests
      run: go test -v ./...

    - name: Generate .env file from secrets
        run: |
          cat <<EOF > .env
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION=us-west-2
          AWS_BUCKET=skripsi-codein
          EOF

    - name: Build Docker Image
      run: docker build -t nikiaprian/backend:latest .

    - name: Docker Login
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Push to Docker Hub
      run: docker push nikiaprian/backend:latest
