name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t nikiaprian/backend:latest .
      
    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push to Docker Hub
      run: docker push nikiaprian/backend:latest

    # - name: Deploy to EC2
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.EC2_HOST }}
    #     username: ${{ secrets.EC2_USERNAME }}
    #     key: ${{ secrets.EC2_PRIVATE_KEY }}
    #     script: |
    #       sudo docker pull nikiaprian/backend:latest
    #       sudo docker stop backend || true
    #       sudo docker rm backend || true
    #       sudo docker run -d --name backend -p 9090:9090 nikiaprian/backend:latest
